on: [push]

jobs:
  a:
    name: a
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: "false"
    steps:
      - run: echo "A"
  b:
    name: a
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - a
    if: ${{ success() || failure() }}
    steps:
      - run: echo "B"
      - id: set
        run: |
          echo "::set-output name=run_job_c::yes"
    outputs:
      run_job_c: ${{ steps.set.outputs.run_job_c }}
  c:
    name: c
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - b
    if: ${{ success() || failure() }} && needs.b.outputs.run_job_c == 'yes'
    steps:
      - run: echo "C"
  d:
    name: d
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - b
      - c
    if: ${{ success() || failure() }} && needs.c.result == 'success'
    steps:
      - run: echo "D"