on: [push]

jobs:
  a:
    name: skipped-job
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: "false"
    steps:
      - run: echo "A"
  b:
    name: succes-job
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - a
    if: ${{ success() || failure() }}
    steps:
      - run: echo "B"
      - name: mkdir
        id: mkdir
        run: |
          mkdir hoge
          # mkdir hoge
  c:
    name: test-job
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - b
    if: ${{ success() || failure() }} && needs.b.result == 'success'
    steps:
      - run: echo "C"
