on: [push]

jobs:
  a:
    name: a
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - run: echo "A"
      - id: set
        run: |
          echo "::set-output name=run_job_b::yes"
    outputs:
      run_job_b: ${{ steps.set.outputs.run_job_b }}
  b:
    name: b
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - a
    if: needs.a.outputs.run_job_b == 'yes'
    steps:
      - run: echo "B"
  c:
    name: c
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - a
      - b
    if: needs.b.result == 'success'
    steps:
      - run: echo "C"